(function(w){
var s={apiKey:null,apiHost:null,environmentId:null,workspace:null,userId:null,email:null,attributes:{},hiddenFields:{},queue:[]};
try{s.queue=JSON.parse(w.localStorage.getItem('feedbackos-sdk-events')||'[]')}catch{}
function save(){try{w.localStorage.setItem('feedbackos-sdk-events',JSON.stringify(s.queue.slice(-100)))}catch{}}
function event(type,payload){var e={id:'evt-'+Math.random().toString(36).slice(2),type:type,payload:payload||{},context:{environmentId:s.environmentId,workspace:s.workspace,userId:s.userId,email:s.email,attributes:s.attributes,hiddenFields:s.hiddenFields},createdAt:new Date().toISOString()};s.queue.push(e);save();try{w.dispatchEvent(new CustomEvent('feedbackos:event',{detail:e}))}catch{};return e}
function post(e){if(!s.apiHost)return;try{w.fetch(String(s.apiHost).replace(/\/$/,'')+'/api/v1/client/events',{method:'POST',keepalive:true,headers:{'content-type':'application/json','x-api-key':s.apiKey||''},body:JSON.stringify(e)}).catch(function(){})}catch{}}
function emit(t,p){var e=event(t,p);post(e);return e}
function widget(o){o=o||{};var old=document.querySelector('[data-feedbackos-widget]');if(old)old.remove();var el=document.createElement('section');el.setAttribute('data-feedbackos-widget','true');el.style.cssText='position:fixed;right:20px;bottom:20px;z-index:99999;width:min(380px,calc(100vw - 40px));background:#fff;border:1px solid #d9e1db;border-radius:8px;box-shadow:0 18px 50px rgba(21,32,27,.18);font-family:Arial,Helvetica,sans-serif;color:#15201b;overflow:hidden';el.innerHTML='<div style="padding:14px 16px;border-bottom:1px solid #d9e1db;display:flex;justify-content:space-between;gap:12px"><strong>'+(o.title||'Share feedback')+'</strong><button aria-label="Close feedback" data-close style="border:0;background:transparent;font-size:18px;cursor:pointer">x</button></div><div style="padding:16px;display:grid;gap:10px"><label style="display:grid;gap:6px;font-size:13px;font-weight:700">Score<input data-score type="number" min="0" max="10" value="8" style="padding:9px;border:1px solid #cbd6cf;border-radius:8px"></label><label style="display:grid;gap:6px;font-size:13px;font-weight:700">Comment<textarea data-comment style="min-height:90px;padding:9px;border:1px solid #cbd6cf;border-radius:8px;resize:vertical"></textarea></label><button data-submit style="border:0;border-radius:8px;background:#15201b;color:white;font-weight:700;padding:10px">Submit response</button><p data-status style="margin:0;color:#66736c;font-size:12px">FeedbackOS</p></div>';document.body.appendChild(el);emit('survey.displayed',{surveyId:o.surveyId||'default'});el.querySelector('[data-close]').addEventListener('click',function(){emit('survey.dismissed',{surveyId:o.surveyId||'default'});el.remove()});el.querySelector('[data-submit]').addEventListener('click',function(){emit('response.created',{surveyId:o.surveyId||'default',score:Number(el.querySelector('[data-score]').value),comment:el.querySelector('[data-comment]').value});el.querySelector('[data-status]').textContent='Response captured. Thank you.';setTimeout(function(){el.remove()},900)})}
w.FeedbackOS={init:function(c){c=c||{};s.apiKey=c.apiKey||c.clientKey||null;s.apiHost=c.apiHost||c.host||null;s.environmentId=c.environmentId||c.workspaceId||null;s.workspace=c.workspace||c.project||null;emit('sdk.initialized',{environmentId:s.environmentId,workspace:s.workspace});return w.FeedbackOS},identify:function(id,a){s.userId=id||s.userId;s.attributes=Object.assign({},s.attributes,a||{});if(a&&a.email)s.email=a.email;emit('contact.identified',{userId:s.userId,attributes:s.attributes});return w.FeedbackOS},setUserId:function(id){s.userId=id;emit('contact.user_id_set',{userId:id});return w.FeedbackOS},setEmail:function(email){s.email=email;emit('contact.email_set',{email:email});return w.FeedbackOS},setAttributes:function(a){s.attributes=Object.assign({},s.attributes,a||{});emit('contact.attributes_set',{attributes:s.attributes});return w.FeedbackOS},setHiddenFields:function(f){s.hiddenFields=Object.assign({},s.hiddenFields,f||{});emit('survey.hidden_fields_set',{hiddenFields:s.hiddenFields});return w.FeedbackOS},track:function(n,p){emit('product.event',{name:n,properties:p||{}});return w.FeedbackOS},showSurvey:function(o){if(typeof o==='string')o={surveyId:o};widget(o||{});return w.FeedbackOS},dismissSurvey:function(){var el=document.querySelector('[data-feedbackos-widget]');if(el)el.remove();emit('survey.dismissed',{});return w.FeedbackOS},getWorkspaceState:function(){return{actionClasses:s.queue.filter(function(e){return e.type==='product.event'}),displays:s.queue.filter(function(e){return e.type==='survey.displayed'}),segments:[],surveys:[],project:{environmentId:s.environmentId,workspace:s.workspace},recaptchaSiteKey:null}},getQueue:function(){return s.queue.slice()},reset:function(){s.userId=null;s.email=null;s.attributes={};s.hiddenFields={};s.queue=[];save();return w.FeedbackOS}};
})(window);
